const data = {
  categories: [
    {
      name: 'Beverages',
      image: '/images/beverages.jpg',
    },
    {
      name: 'Breakfast',
      image: '/images/breakfast.jpg',
    },
    {
      name: 'Burgers',
      image: '/images/burgers.jpg',
    },
  ],
  products: [
    {
      category: 'Beverages',
      name: 'Coca-Cola',
      calorie: 120,
      price: 1,
      image: '/images/t-mcdonalds-Coca-Cola-Classic-Small.jpg',
      disabledimage:'/images/cocacola.png',
      initstock:5,
      stock:5,
    },
    {
      category: 'Beverages',
      name: 'Vanill Shake',
      price: 1.5,
      calorie: 360,
      image: '/images/t-mcdonalds-Vanilla-McCafe-Shake-Medium.jpg',
      disabledimage:'/images/vanila.png',
      initstock:50,
      stock:50,
    },
    {
      category: 'Beverages',
      name: 'Hot Chocolate',
      price: 2,
      calorie: 170,
      image: '/images/t-mcdonalds-McCafe-Hot-Chocolate-Medium.jpg',
      disabledimage:'/images/mccafe.png',
      initstock:50,
      stock:50,
    },
    {
      category: 'Breakfast',
      name: 'Bacon & Biscuit',
      price: 1.9,
      calorie: 90,
      image: '/images/t-mcdonalds-Bacon-Egg-Cheese-Biscuit-Regular-Size-Biscuit.jpg',
      disabledimage:'/images/bacon.png',
      initstock:50,
      stock:50,
    },
    {
      category: 'Breakfast',
      name: 'Blueberry Muffin',
      price: 1.5,
      calorie: 120,
      image: '/images/t-blueberry-muffin.jpg',
      disabledimage:'/images/muffin.png',
      initstock:50,
      stock:50,
    },
    {
      category: 'Breakfast',
      name: 'Big Breakfast',
      price: 3,
      calorie: 430,
      image: '/images/s-mcdonalds-Big-Breakfast-Regular-Size-Biscuit.jpg',
      disabledimage:'/images/breakfast.png',
      initstock:50,
      stock:50,
    },
    {
      category: 'Burgers',
      name: 'Big Mac',
      price: 1.9,
      calorie: 200,
      image: '/images/t-mcdonalds-Big-Mac.jpg',
      disabledimage:'/images/bigmac.png',
      initstock:50,
      stock:50,
    },
    {
      category: 'Burgers',
      name: 'Hamburger',
      price: 1.5,
      calorie: 410,
      image: '/images/t-mcdonalds-Hamburger.jpg',
      disabledimage:'/images/burger.png',
      initstock:50,
      stock:50,
    },
    {
      category: 'Burgers',
      name: 'McDouble',
      price: 3,
      calorie: 320,
      image: '/images/t-mcdonalds-McDouble.jpg',
      disabledimage:'/images/mcdouble.png',
      initstock:50,
      stock:50,
    },
  ],
};

module.exports = data;